# Generated by Django 6.1.1 on 2026-10-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, max_length=100, verbose_name='شرکت حمل'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل'),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('new', 'در انتظار آماده\u200cسازی'), ('processing', 'در حال آماده\u200cسازی'), ('shipped', 'ارسال\u200cشده'), ('delivered', 'تحویل\u200cشده')], default='new', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='processing_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='شروع آماده\u200cسازی'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='کد رهگیری'),
        ),
    ]
