# Generated by Django 5.2.17 on 2026-10-02 17:45

import django.db.models.deletion
from django.db import migrations, models


def link_existing_items(apps, schema_editor):
    Item = apps.get_model("orders", "OrderItem")
    Variant = apps.get_model("products", "ProductVariant")
    db = schema_editor.connection.alias
    variants = {v.product_id: v for v in Variant.objects.using(db).filter(is_default=True)}
    for item in Item.objects.using(db).filter(variant_id__isnull=True).iterator():
        variant = variants.get(item.product_id)
        if variant:
            item.variant_id = variant.id
            item.size = variant.size
            item.cart_key = f"v:{variant.id}"
            item.save(using=db, update_fields=["variant", "size", "cart_key"])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_fulfillment'),
        ('products', '0007_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cart_key',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productvariant'),
        ),
        migrations.RunPython(link_existing_items, migrations.RunPython.noop),
    ]
