# Generated by Django 6.1.1 on 2026-10-02 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_align_bigauto_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='تصویر دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='برای منوی اصلی خالی بگذارید؛ برای زیرمنو، والد را انتخاب کنید.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.category', verbose_name='دسته\u200cبندی والد'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_menu',
            field=models.BooleanField(default=True, verbose_name='نمایش در منو'),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='عدد کمتر، زودتر نمایش داده می\u200cشود.', verbose_name='ترتیب نمایش'),
        ),
    ]
