# Generated by Django 6.1.1 on 2026-10-02 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_options_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='برای منوی اصلی خالی بگذارید. برای زیرمنو، دسته\u200cبندی والد را انتخاب کنید.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.category', verbose_name='دسته\u200cبندی والد'),
        ),
    ]
