# Generated by Django 5.2.17 on 2026-10-02 17:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def seed_existing_variants(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Variant = apps.get_model("products", "ProductVariant")
    db = schema_editor.connection.alias
    for product in Product.objects.using(db).iterator():
        Variant.objects.using(db).get_or_create(product_id=product.id, is_default=True, defaults={
            "sku": product.sku, "color": product.color, "size": product.size,
            "price": product.price, "stock": product.stock, "is_active": product.is_active,
        })


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='کد تنوع')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='رنگ')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='سایز')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/variants/', verbose_name='تصویر رنگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_default', models.BooleanField(default=False, verbose_name='تنوع اولیه برای سبدهای قدیمی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'رنگ و سایز محصول',
                'verbose_name_plural': 'رنگ\u200cها و سایزهای محصول',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('product', 'color', 'size'), name='unique_product_color_size'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('product',), name='one_legacy_default_variant'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='variant_price_nonnegative')],
            },
        ),
        migrations.RunPython(seed_existing_variants, migrations.RunPython.noop),
    ]

