# Generated by Django 6.1.1 on 2026-10-03 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='color_hex',
            field=models.CharField(blank=True, help_text='رنگ نمایشی دایرهٔ پالت را انتخاب کنید.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'کد رنگ باید مانند #800020 باشد.')], verbose_name='رنگ پالت'),
        ),
    ]
