# Generated by Django 5.2.17 on 2026-10-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس صفحه')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشرشده')),
            ],
            options={
                'verbose_name': 'صفحه اطلاعات',
                'verbose_name_plural': 'صفحات اطلاعات',
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='فروشگاه چرم', max_length=100, verbose_name='نام فروشگاه')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='شماره واتساپ')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='آیدی اینستاگرام')),
                ('address', models.TextField(blank=True, verbose_name='آدرس فروشگاه')),
                ('hours', models.CharField(blank=True, max_length=200, verbose_name='ساعات پاسخ\u200cگویی')),
                ('price_unit', models.CharField(default='واحد قیمت فروشگاه', max_length=30, verbose_name='واحد مبالغ')),
            ],
            options={
                'verbose_name': 'تنظیمات فروشگاه',
                'verbose_name_plural': 'تنظیمات فروشگاه',
            },
        ),
    ]

